site_name:        "Bootstrap 5 test page"
site_author:      "redtide"
site_url:         "https://redtide.github.io/bootstrap5-test-page"
site_dir:         "_site_mkdocs"
site_description:
  "Sample page for Bootstrap 5 components.
  Try out the default theme or your custom stylesheet."

repo_name:        "GitHub"
repo_url:         "https://github.com/redtide/bootstrap5-test-page"
edit_uri:         "edit/mkdocs/docs/"
remote_branch:    "www"

copyright:
  'Bootstrap 5 test page by <a href="https://redtide.github.io/">redtide</a>'

extra_css:
- "css/docs.css"

extra_javascript:
- "js/color-modes.js"

theme:
  name:        null
  base_url:   "bootstrap5-test-page"
  custom_dir: "layout"
  highlightjs: true
  hljs_light: "github"
  hljs_dark:  "github-dark-dimmed"
  nav_style:  "dark"
  locale:     "en"
  bootstrap_version: "5.3"

plugins:
  macros:
    include_yaml:
    - colors:    "data/colors.yml"
    - sections:  "data/sections.yml"
    include_dir: "include"
    verbose: true

watch:
- docs
- layout

nav:
- "index.md"
